import type { FeatureCollection, MultiPolygon, Polygon } from "geojson";
import type { Topology } from "topojson-specification";
import { feature } from "topojson-client";

import rawCountries from "@/data/world-countries.meta.json";
import type { ContinentId } from "@/lib/types";

export type CountryKind = "country" | "dependency" | "disputed" | "region";

/** One entry per shape on the world map, generated by scripts/build-world-data.mjs. */
export interface CountryMeta {
  /** Natural Earth ADM0_A3 code, also the id of the matching map shape. */
  id: string;
  name: string;
  nameEn: string;
  officialName?: string;
  iso2?: string;
  iso3?: string;
  /** Wikidata item, used for the live fact lookup. */
  qid?: string;
  /** German Wikipedia article title. */
  title: string;
  kind: CountryKind;
  continent: ContinentId | null;
  /** Set for dependencies: the state they belong to. */
  sovereign?: string;
  lon: number;
  lat: number;
  capital?: string;
  languages?: string;
  currency?: string;
  government?: string;
  population?: number;
  areaKm2?: number;
}

export type CountryProperties = {
  id: string;
  name: string;
  kind: CountryKind;
  continent: ContinentId | null;
};

export type WorldCollection = FeatureCollection<
  Polygon | MultiPolygon,
  CountryProperties
>;

export const WORLD_COUNTRIES = rawCountries as CountryMeta[];

const BY_ID = new Map(WORLD_COUNTRIES.map((country) => [country.id, country]));

export const kindLabels: Record<CountryKind, string> = {
  country: "Staat",
  dependency: "Außengebiet",
  disputed: "Umstrittener Status",
  region: "Region",
};

export function countryById(id: string | null | undefined): CountryMeta | null {
  if (!id) return null;
  return BY_ID.get(id) ?? null;
}

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

const SEARCH_INDEX = WORLD_COUNTRIES.map((country) => ({
  country,
  haystack: normalize(
    [
      country.name,
      country.nameEn,
      country.officialName ?? "",
      country.capital ?? "",
      country.iso2 ?? "",
      country.iso3 ?? "",
    ].join(" ")
  ),
  start: normalize(country.name),
}));

export function searchCountries(query: string, limit = 60): CountryMeta[] {
  const q = normalize(query);
  if (!q) {
    return WORLD_COUNTRIES.filter((country) => country.kind === "country").slice(
      0,
      limit
    );
  }
  const scored: { country: CountryMeta; score: number }[] = [];
  for (const entry of SEARCH_INDEX) {
    if (!entry.haystack.includes(q)) continue;
    let score = 0;
    if (entry.start === q) score += 100;
    else if (entry.start.startsWith(q)) score += 50;
    if (entry.country.kind === "country") score += 10;
    scored.push({ country: entry.country, score });
  }
  scored.sort(
    (a, b) =>
      b.score - a.score || a.country.name.localeCompare(b.country.name, "de")
  );
  return scored.slice(0, limit).map((entry) => entry.country);
}

export function randomCountry(exclude?: string | null): CountryMeta {
  const pool = WORLD_COUNTRIES.filter(
    (country) =>
      country.kind === "country" &&
      (country.population ?? 0) > 0 &&
      country.id !== exclude
  );
  return pool[Math.floor(Math.random() * pool.length)];
}

export function countriesOnContinent(
  continent: ContinentId,
  sovereignOnly = true
): CountryMeta[] {
  return WORLD_COUNTRIES.filter(
    (country) =>
      country.continent === continent &&
      (!sovereignOnly || country.kind === "country")
  ).sort((a, b) => a.name.localeCompare(b.name, "de"));
}

const numberFormat = new Intl.NumberFormat("de-DE");

export function formatNumber(value: number): string {
  return numberFormat.format(value);
}

export function formatPopulation(value: number): string {
  return `${numberFormat.format(Math.round(value))} Einwohner`;
}

export function formatArea(value: number): string {
  const rounded =
    value >= 1000
      ? Math.round(value)
      : Math.round(value * 100) / 100;
  return `${numberFormat.format(rounded)} km²`;
}

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export const WORLD_TOPOLOGY_URL = `${BASE_PATH}/data/world-countries.topo.json`;

let topologyPromise: Promise<WorldCollection> | null = null;

/**
 * The topology is ~550 kB, so it lives in /public and is fetched once per
 * session instead of being bundled into the page chunk.
 */
export function loadWorldCollection(): Promise<WorldCollection> {
  if (!topologyPromise) {
    topologyPromise = fetch(WORLD_TOPOLOGY_URL)
      .then(async (response) => {
        if (!response.ok) {
          throw new Error(`Kartendaten nicht erreichbar (${response.status})`);
        }
        const topology = (await response.json()) as Topology;
        return feature(
          topology,
          topology.objects.countries
        ) as unknown as WorldCollection;
      })
      .catch((error) => {
        topologyPromise = null;
        throw error;
      });
  }
  return topologyPromise;
}
